services:
  trainer:
    build: ./services/trainer
    container_name: ds_trainer
    volumes:
      - model_data:/models
    environment:
      - MLFLOW_TRACKING_URI=http://ds_mlflow:5000
      - MLFLOW_EXPERIMENT_NAME=iris-demo
    depends_on:
      - mlflow
    restart: "no"

  api:
    build: ./services/api
    container_name: ds_api
    ports:
      - "8000:8000"
    volumes:
      - model_data:/models
    depends_on:
      - trainer 

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: ds_mlflow
    ports:
      - "5000:5000"
    command:
      - mlflow
      - server
      - --host=0.0.0.0
      - --port=5000
      - --backend-store-uri=sqlite:////mlflow/mlflow.db
      - --default-artifact-root=/mlflow/artifacts
      - --serve-artifacts
      - --allowed-hosts=localhost,localhost:5000,127.0.0.1,127.0.0.1:5000,ds_mlflow,ds_mlflow:5000,mlflow,mlflow:5000


    volumes:
      - mlflow_data:/mlflow   
      - mlflow_artifacts:/mlflow/artifacts

volumes:
  model_data:
  mlflow_data:
  mlflow_artifacts:

