services:
  trainer:
    build: ./services/trainer
    container_name: ds_trainer
    volumes:
      - model_data:/models
    restart: "no"

  api:
    build: ./services/api
    container_name: ds_api
    ports:
      - "8000:8000"
    volumes:
      - model_data:/models
    depends_on:
      - trainer 

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: ds_mlflow
    ports:
      - "5000:5000"
    command:
      - mlflow
      - server
      - --host=0.0.0.0
      - --port=5000
      - --backend-store-uri=sqlite:////mlflow/mlflow.db
      - --default-artifact-root=/mlflow/artifacts
      - --gunicorn-opts=--forwarded-allow-ips=*
    volumes:
      - mlflow_data:/mlflow   

volumes:
  model_data:
  mlflow_data:

